### ISSUE TITLE
Missing kaspa_db_filler project

### ISSUE THREAD

**Issue by tonik-ru** [kaspa-ng/kaspa-rest-server#21]
hi. is kaspa_db_filler available? old version has outdated schema. and rest server doesnt work with it.
and do you provide docker image for current version of server?

**Comment by supertypo** [comment]
New filler is closed source for now. Its available as a docker image only.
A rest server which is compatible with the old python filler is available here: 
https://github.com/lAmeR1/kaspa-rest-server-deprecated
